

----------------PART-1------------------------------
select * from sales.customers;
--------------------------------------------------------------------------------
--1. Brand Listing Write a query to list all product names along with
-- their corresponding
--brand names. Sort the results alphabetically by brand name.

select pp.product_name,pd.brand_name
from production.products pp join production.brands pd
on pp.brand_id = pd.brand_id
order by brand_name;

------------------------------------------------------------------------
--2. Store Contact List Retrieve a list of all staff members, including their first 
-- and last names, and the store name where they work

select sstf.first_name,sstf.last_name,sst.store_name
from sales.staffs sstf join sales.stores sst
on sstf.store_id = sst.store_id;

----------------------------------------------------------------------------------
--3. Customer Order History Show all orders (order ID and order date) along with the
--customer's full name (first and last) who placed them. Order the results by the order date
--in descending order (most recent first).


 select so.order_id, so.order_date, concat(sc.first_name,' ',sc.last_name) as full_name
 from sales.orders so join sales.customers sc 
 on so.customer_id = sc.customer_id
 order by so.order_date DESC;
 

 
 ----------PART-2-------------------------------------------------------------------------------
--4. Category Stock Levels Calculate the total quantity of products in stock for each
--category name. Group the results by category and use a HAVING clause to only show
--categories that have more than 500 items in total stock.


SELECT category_name,sum(quantity) as total_stoke
from production.stocks ps join production.products pp
on ps.product_id = pp.product_id
join production.categories pc
on pp.category_id = pc.category_id
group by pc.category_name
having sum(quantity)>500;
 -----------------------------------------------------------------------------------------------------------------------
 --5. Sales Performance by Store Find the total sales amount (calculated as quantity *
--list_price) generated by each store. Display the store name and the total sales revenue,
--ordered from the highest revenue to the lowest.
 
-- incorrect logic

select (ps.quantity*pp.list_price) as total_sales_revenue, ss.store_name
from sales.stores ss 
join production.stocks ps on ss.store_id = ps.store_id
join production.products pp on ps.product_id = pp.product_id
order by (ps.quantity*pp.list_price) desc;
 
 --correct logic flow
 --join flow,stores → orders → order_items

 select ss.store_name, sum(quantity*list_price) as total_sales_revenue 
 from sales.stores ss join sales.orders so
 on ss.store_id =so.store_id
 join sales.order_items soi
 on so.order_id = soi.order_id
 group by ss.store_name
 order by total_sales_revenue  desc;


 -------------------------------------------------------------------------------------------------------------------------------------------------

-- 6. Product Pricing Tiers List all products, their category names, and their list prices.
 --Use a CASE statement to create a new column called 'Price_Segment' that labels them as:
--'Budget' (if price is under $500)
--'Mid-Range' (if price is between $500 and $2000)
--'Premium' (if price is over $2000)

--core logic is here
select pp.product_name,pc.category_name,pp.list_price,
   CASE
        WHEN pp.list_price <500 THEN 'Budget'
        WHEN pp.list_price  between 500 and 2000 THEN 'Mid-Range'
        WHEN pp.list_price > 2000 THEN 'Premium'
        ELSE 'unknown'
   END as price_segment
from production.products pp join production.categories pc
on pp.category_id = pc.category_id;


----------------------------------------------------------------------------------------

--7. Bulk Order Summary For each order, find the total number of distinct products ordered.
--Display the Order ID and the Product Count, but only for orders that contain more than 3
--different products.
SELECT 
    so.order_id,
    COUNT(DISTINCT soi.product_id) AS product_count
FROM sales.orders so
JOIN sales.order_items soi
    ON so.order_id = soi.order_id
GROUP BY so.order_id
HAVING COUNT(DISTINCT soi.product_id) > 3;


------------------------------------------------------------------------------------
------------------part-3----------------------
--8. Brand Performance Analysis Identify the brands that have sold more than 100 units in
--total. Your output should include the Brand Name, the total Quantity Sold, and a CASE
--statement that flags the brand as "Top Performer" if sales exceed 500 units, and
--"Standard" otherwise. (Hint: Join brands, products, and order_items)


 select pb.brand_name,sum(soi.quantity) as total_quantity,
  case
    when SUM(soi.quantity) >500 then 'TOP Performer'
    else 'Standard'
  end as performance_flag
 from production.brands pb join production.products pp
 on pb.brand_id =pp.brand_id
 join sales.order_items soi
 on pp.product_id = soi.product_id
 group by pb.brand_name                   --Column 'production.brands.brand_name' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
 HAVING SUM(soi.quantity) > 100;





 ---------------------------------------------------------------------------------------------------------------------------------------------------
-- 9. Staff Sales Activity Find all staff members who have handled more than 50 orders.
--Display their full name (concatenated), their store name, and the total count of orders they
--processed. Sort the output alphabetically by store name, and then by the order count in
--descending order.

--staff Sales activity

	select concat(ss.first_name ,' ' ,ss.last_name) AS full_name,store_name,count(order_id) as total_number_of_orders
	from sales.staffs ss join sales.orders so
	on ss.staff_id = so.staff_id
	join sales.stores sst
	on so.store_id = sst.store_id
	group by ss.staff_id, ss.first_name, ss.last_name, sst.store_name
	having count(so.order_id)>50 
	order by sst.store_name asc, count(order_id) desc;

	---------------------------------------------------------------------------
--Discount Impact Analysis

--Analyze the revenue lost due to discounts across different product categories.
--For each product category, calculate:
--The total potential revenue (assuming no discounts were applied).
--The actual revenue (after applying the discount).
--The total discount amount (the total revenue lost due to discounts).

--Use GROUP BY to aggregate the data by category, and HAVING to display only those categories where the total discount amount exceeds $5,000.



SELECT 
    pc.category_name,
    SUM(soi.quantity * soi.list_price) AS total_potential_revenue,  -- Potential revenue (no discount)
    SUM(soi.quantity * soi.list_price * (1 - soi.discount)) AS actual_revenue,  -- Actual revenue (after discount)
    SUM(soi.quantity * soi.list_price *soi.discount) AS total_discount_amount     -- Total discount amount (revenue lost)
FROM sales.order_items soi
JOIN production.products pp
    ON soi.product_id = pp.product_id
JOIN production.categories pc
    ON pp.category_id = pc.category_id
GROUP BY pc.category_name
HAVING SUM(soi.quantity * soi.list_price * soi.discount) > 5000
ORDER BY 
    total_discount_amount DESC;

---------------------------------------------end------------------------------------------------------------------------------------------------